name: Publish Node Docker
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
build:
  runs-on: ubuntu-lastest
  steps:
  - uses: actions/checkout@v1
  - name: Build & Push Image
    run:
      echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password=stdin
      docker image -build -t "${{ secrets.DOCKERUSERNAME }}/
      EGCI341GIT:lastest" .
      docker push "{{ secrets.DOCKERUSERNAME }}/EGCI341GIT:lastest"